task: image_semantic_segmentation
base_model: nvidia/mit-b0
project_name: autotrain-image-semantic-segmentation-model
log: tensorboard
backend: local

data:
  path: data/
  train_split: train # this folder inside data/ will be used for training, it contains the images and masks.
  valid_split: null
  column_mapping:
    image_column: image
    target_column: segmentation_mask

params:
  epochs: 3
  batch_size: 1
  lr: 5e-5
  optimizer: adamw_torch
  scheduler: linear
  gradient_accumulation: 1
  mixed_precision: fp16
  ignore_mismatched_sizes: true
  reduce_labels: false

hub:
  username: ${HF_USERNAME}
  token: ${HF_TOKEN}
  push_to_hub: true 